spring:
  application:
    name: JobAssistant
  #DataSource Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobassistant
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  #session 失效时间
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api